spring:

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8081/realms/kateringapp
          jwk-set-uri: http://keycloak:8081/realms/kateringapp/protocol/openid-connect/certs

  datasource:
     url: jdbc:postgresql://backend-db:5432/backend-db
     username: postgres
     password: postgres
  jpa:
     database-platform: org.hibernate.dialect.PostgreSQLDialect
     hibernate:
       ddl-auto: create-drop
     defer-datasource-initialization: true
  sql:
     init:
       mode: always

#  h2:
#    console.enabled: true # http://localhost:8080/h2-console
#  datasource:
#    url: jdbc:h2:mem:db;MODE=PostgreSQL
#    username: sa
#    password: sa
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true